// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azphpzwalortrhrzqfou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6cGhwendhbG9ydHJocnpxZm91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTA0MjksImV4cCI6MjA2Mjg2NjQyOX0.ifa77hwBseuo9OUtsNuN78RXMeDx3cmx_fEUBIWXA0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);